sonar.projectKey=fintech-core-frontend
sonar.projectName=Fintech Core Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
# Exclui da análise o cliente HTTP gerado pelo Orval (código gerado não se cobra)
sonar.exclusions=src/app/core/api/**
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.sourceEncoding=UTF-8
