/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Fintech SaaS API
 * API de gestão financeira multi-tenant.
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  BudgetCycleOpenRequest,
  BudgetCyclePageResponse,
  BudgetCycleResponse,
  BudgetItemCreateRequest,
  BudgetItemLinkRequest,
  BudgetItemResponse,
  BudgetItemUpdateRequest,
  ListBudgetCyclesParams,
  RecurringBudgetItemRequest,
  RecurringBudgetItemResponse
} from '../fintechSaaSAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable({ providedIn: 'root' })
export class BudgetService {
  private readonly http = inject(HttpClient);
 listBudgetCycles<TData = BudgetCyclePageResponse>(params?: ListBudgetCyclesParams, options?: HttpClientBodyOptions): Observable<TData>;
 listBudgetCycles<TData = BudgetCyclePageResponse>(params?: ListBudgetCyclesParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listBudgetCycles<TData = BudgetCyclePageResponse>(params?: ListBudgetCyclesParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listBudgetCycles<TData = BudgetCyclePageResponse>(
    params?: ListBudgetCyclesParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/budget-cycles`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/budget-cycles`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/budget-cycles`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
 openBudgetCycle<TData = BudgetCycleResponse>(budgetCycleOpenRequest: BudgetCycleOpenRequest, options?: HttpClientBodyOptions): Observable<TData>;
 openBudgetCycle<TData = BudgetCycleResponse>(budgetCycleOpenRequest: BudgetCycleOpenRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 openBudgetCycle<TData = BudgetCycleResponse>(budgetCycleOpenRequest: BudgetCycleOpenRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  openBudgetCycle<TData = BudgetCycleResponse>(
    budgetCycleOpenRequest: BudgetCycleOpenRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/budget-cycles`,
      budgetCycleOpenRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/budget-cycles`,
      budgetCycleOpenRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/budget-cycles`,
      budgetCycleOpenRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getCurrentBudgetCycle<TData = BudgetCycleResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 getCurrentBudgetCycle<TData = BudgetCycleResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getCurrentBudgetCycle<TData = BudgetCycleResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getCurrentBudgetCycle<TData = BudgetCycleResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/budget-cycles/current`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/budget-cycles/current`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/budget-cycles/current`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getBudgetCycle<TData = BudgetCycleResponse>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getBudgetCycle<TData = BudgetCycleResponse>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getBudgetCycle<TData = BudgetCycleResponse>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getBudgetCycle<TData = BudgetCycleResponse>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/budget-cycles/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/budget-cycles/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/budget-cycles/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 closeBudgetCycle<TData = BudgetCycleResponse>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 closeBudgetCycle<TData = BudgetCycleResponse>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 closeBudgetCycle<TData = BudgetCycleResponse>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  closeBudgetCycle<TData = BudgetCycleResponse>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/budget-cycles/${id}/close`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/budget-cycles/${id}/close`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/budget-cycles/${id}/close`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 syncInstallments<TData = BudgetCycleResponse>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 syncInstallments<TData = BudgetCycleResponse>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 syncInstallments<TData = BudgetCycleResponse>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  syncInstallments<TData = BudgetCycleResponse>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/budget-cycles/${id}/sync-installments`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/budget-cycles/${id}/sync-installments`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/budget-cycles/${id}/sync-installments`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 listBudgetItems<TData = BudgetItemResponse[]>(cycleId: string, options?: HttpClientBodyOptions): Observable<TData>;
 listBudgetItems<TData = BudgetItemResponse[]>(cycleId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listBudgetItems<TData = BudgetItemResponse[]>(cycleId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listBudgetItems<TData = BudgetItemResponse[]>(
    cycleId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/budget-cycles/${cycleId}/items`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/budget-cycles/${cycleId}/items`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/budget-cycles/${cycleId}/items`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 createBudgetItem<TData = BudgetItemResponse>(cycleId: string,
    budgetItemCreateRequest: BudgetItemCreateRequest, options?: HttpClientBodyOptions): Observable<TData>;
 createBudgetItem<TData = BudgetItemResponse>(cycleId: string,
    budgetItemCreateRequest: BudgetItemCreateRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 createBudgetItem<TData = BudgetItemResponse>(cycleId: string,
    budgetItemCreateRequest: BudgetItemCreateRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  createBudgetItem<TData = BudgetItemResponse>(
    cycleId: string,
    budgetItemCreateRequest: BudgetItemCreateRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/budget-cycles/${cycleId}/items`,
      budgetItemCreateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/budget-cycles/${cycleId}/items`,
      budgetItemCreateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/budget-cycles/${cycleId}/items`,
      budgetItemCreateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 updateBudgetItem<TData = BudgetItemResponse>(id: string,
    budgetItemUpdateRequest: BudgetItemUpdateRequest, options?: HttpClientBodyOptions): Observable<TData>;
 updateBudgetItem<TData = BudgetItemResponse>(id: string,
    budgetItemUpdateRequest: BudgetItemUpdateRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateBudgetItem<TData = BudgetItemResponse>(id: string,
    budgetItemUpdateRequest: BudgetItemUpdateRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateBudgetItem<TData = BudgetItemResponse>(
    id: string,
    budgetItemUpdateRequest: BudgetItemUpdateRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/budget-items/${id}`,
      budgetItemUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/budget-items/${id}`,
      budgetItemUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/budget-items/${id}`,
      budgetItemUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteBudgetItem<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteBudgetItem<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteBudgetItem<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteBudgetItem<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/budget-items/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/budget-items/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/budget-items/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 linkBudgetItem<TData = BudgetItemResponse>(id: string,
    budgetItemLinkRequest: BudgetItemLinkRequest, options?: HttpClientBodyOptions): Observable<TData>;
 linkBudgetItem<TData = BudgetItemResponse>(id: string,
    budgetItemLinkRequest: BudgetItemLinkRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 linkBudgetItem<TData = BudgetItemResponse>(id: string,
    budgetItemLinkRequest: BudgetItemLinkRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  linkBudgetItem<TData = BudgetItemResponse>(
    id: string,
    budgetItemLinkRequest: BudgetItemLinkRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/budget-items/${id}/link`,
      budgetItemLinkRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/budget-items/${id}/link`,
      budgetItemLinkRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/budget-items/${id}/link`,
      budgetItemLinkRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 unlinkBudgetItem<TData = BudgetItemResponse>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 unlinkBudgetItem<TData = BudgetItemResponse>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 unlinkBudgetItem<TData = BudgetItemResponse>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  unlinkBudgetItem<TData = BudgetItemResponse>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/budget-items/${id}/link`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/budget-items/${id}/link`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/budget-items/${id}/link`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 listRecurringBudgetItems<TData = RecurringBudgetItemResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 listRecurringBudgetItems<TData = RecurringBudgetItemResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listRecurringBudgetItems<TData = RecurringBudgetItemResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listRecurringBudgetItems<TData = RecurringBudgetItemResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/recurring-budget-items`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/recurring-budget-items`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/recurring-budget-items`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 createRecurringBudgetItem<TData = RecurringBudgetItemResponse>(recurringBudgetItemRequest: RecurringBudgetItemRequest, options?: HttpClientBodyOptions): Observable<TData>;
 createRecurringBudgetItem<TData = RecurringBudgetItemResponse>(recurringBudgetItemRequest: RecurringBudgetItemRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 createRecurringBudgetItem<TData = RecurringBudgetItemResponse>(recurringBudgetItemRequest: RecurringBudgetItemRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  createRecurringBudgetItem<TData = RecurringBudgetItemResponse>(
    recurringBudgetItemRequest: RecurringBudgetItemRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/recurring-budget-items`,
      recurringBudgetItemRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/recurring-budget-items`,
      recurringBudgetItemRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/recurring-budget-items`,
      recurringBudgetItemRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 updateRecurringBudgetItem<TData = RecurringBudgetItemResponse>(id: string,
    recurringBudgetItemRequest: RecurringBudgetItemRequest, options?: HttpClientBodyOptions): Observable<TData>;
 updateRecurringBudgetItem<TData = RecurringBudgetItemResponse>(id: string,
    recurringBudgetItemRequest: RecurringBudgetItemRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateRecurringBudgetItem<TData = RecurringBudgetItemResponse>(id: string,
    recurringBudgetItemRequest: RecurringBudgetItemRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateRecurringBudgetItem<TData = RecurringBudgetItemResponse>(
    id: string,
    recurringBudgetItemRequest: RecurringBudgetItemRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/recurring-budget-items/${id}`,
      recurringBudgetItemRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/recurring-budget-items/${id}`,
      recurringBudgetItemRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/recurring-budget-items/${id}`,
      recurringBudgetItemRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteRecurringBudgetItem<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteRecurringBudgetItem<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteRecurringBudgetItem<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteRecurringBudgetItem<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/recurring-budget-items/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/recurring-budget-items/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/recurring-budget-items/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

