package com.fintech.api.domain.category;

public enum CategoryTaxonomy {
    // Renda
    INCOME, INCOME_SALARY, INCOME_FREELANCE, INCOME_INVESTMENT_RETURNS, INCOME_REIMBURSEMENT,
    // Moradia
    HOUSING, HOUSING_RENT, HOUSING_CONDO, HOUSING_ENERGY, HOUSING_WATER_GAS, HOUSING_INTERNET,
    // Alimentação
    FOOD, FOOD_GROCERY, FOOD_RESTAURANT, FOOD_DELIVERY, FOOD_BAKERY,
    // Transporte
    TRANSPORT, TRANSPORT_FUEL, TRANSPORT_RIDESHARE, TRANSPORT_PUBLIC,
    TRANSPORT_VEHICLE_TAX, TRANSPORT_VEHICLE_MAINTENANCE,
    // Saúde
    HEALTH, HEALTH_PHARMACY, HEALTH_INSURANCE, HEALTH_APPOINTMENTS, HEALTH_FITNESS, HEALTH_MENTAL,
    // Lazer
    LEISURE, LEISURE_ENTERTAINMENT, LEISURE_TRAVEL, LEISURE_HOBBIES, LEISURE_NIGHTLIFE,
    // Educação
    EDUCATION, EDUCATION_COURSES, EDUCATION_BOOKS, EDUCATION_SCHOOL,
    // Vestuário
    CLOTHING, CLOTHING_APPAREL, CLOTHING_ACCESSORIES, CLOTHING_LAUNDRY,
    // Casa & Decoração
    HOME_GOODS, HOME_GOODS_FURNITURE, HOME_GOODS_UTILITIES, HOME_GOODS_MAINTENANCE,
    // Assinaturas
    SUBSCRIPTIONS, SUBSCRIPTIONS_VIDEO, SUBSCRIPTIONS_MUSIC, SUBSCRIPTIONS_GAMING, SUBSCRIPTIONS_SOFTWARE,
    // Cuidados Pessoais
    PERSONAL_CARE, PERSONAL_CARE_BEAUTY, PERSONAL_CARE_HYGIENE, PERSONAL_CARE_WELLNESS,
    // Pets
    PETS, PETS_FOOD, PETS_VET, PETS_GROOMING,
    // Financeiro
    FINANCIAL, FINANCIAL_TAXES, FINANCIAL_BANK_FEES, FINANCIAL_LOANS, FINANCIAL_INSURANCE,
    // Presentes e Doações
    GIFTS, GIFTS_PRESENTS, GIFTS_DONATIONS
}
