/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Fintech SaaS API
 * API de gestão financeira multi-tenant.
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  ConfirmOccurrenceDTO,
  RecurrenceRuleCreateDTO,
  RecurrenceRulePatchDTO,
  RecurrenceRuleResponseDTO,
  TransactionResponseDTO
} from '../fintechSaaSAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class RecurrenceRulesService {
  private readonly http = inject(HttpClient);
/**
 * @summary Lista as regras de recorrência ativas do tenant
 */
 listRecurrenceRules<TData = RecurrenceRuleResponseDTO[]>( options?: HttpClientBodyOptions): Observable<TData>;
 listRecurrenceRules<TData = RecurrenceRuleResponseDTO[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listRecurrenceRules<TData = RecurrenceRuleResponseDTO[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listRecurrenceRules<TData = RecurrenceRuleResponseDTO[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/recurrence-rules`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/recurrence-rules`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/recurrence-rules`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 createRecurrenceRule<TData = RecurrenceRuleResponseDTO>(recurrenceRuleCreateDTO: RecurrenceRuleCreateDTO, options?: HttpClientBodyOptions): Observable<TData>;
 createRecurrenceRule<TData = RecurrenceRuleResponseDTO>(recurrenceRuleCreateDTO: RecurrenceRuleCreateDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 createRecurrenceRule<TData = RecurrenceRuleResponseDTO>(recurrenceRuleCreateDTO: RecurrenceRuleCreateDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  createRecurrenceRule<TData = RecurrenceRuleResponseDTO>(
    recurrenceRuleCreateDTO: RecurrenceRuleCreateDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/recurrence-rules`,
      recurrenceRuleCreateDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/recurrence-rules`,
      recurrenceRuleCreateDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/recurrence-rules`,
      recurrenceRuleCreateDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getRecurrenceRule<TData = RecurrenceRuleResponseDTO>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getRecurrenceRule<TData = RecurrenceRuleResponseDTO>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getRecurrenceRule<TData = RecurrenceRuleResponseDTO>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getRecurrenceRule<TData = RecurrenceRuleResponseDTO>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/recurrence-rules/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/recurrence-rules/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/recurrence-rules/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 patchRecurrenceRule<TData = RecurrenceRuleResponseDTO>(id: string,
    recurrenceRulePatchDTO: RecurrenceRulePatchDTO, options?: HttpClientBodyOptions): Observable<TData>;
 patchRecurrenceRule<TData = RecurrenceRuleResponseDTO>(id: string,
    recurrenceRulePatchDTO: RecurrenceRulePatchDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 patchRecurrenceRule<TData = RecurrenceRuleResponseDTO>(id: string,
    recurrenceRulePatchDTO: RecurrenceRulePatchDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  patchRecurrenceRule<TData = RecurrenceRuleResponseDTO>(
    id: string,
    recurrenceRulePatchDTO: RecurrenceRulePatchDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/recurrence-rules/${id}`,
      recurrenceRulePatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/recurrence-rules/${id}`,
      recurrenceRulePatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/recurrence-rules/${id}`,
      recurrenceRulePatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 cancelRecurrenceRule<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 cancelRecurrenceRule<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 cancelRecurrenceRule<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  cancelRecurrenceRule<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/recurrence-rules/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/recurrence-rules/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/recurrence-rules/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 reactivateRecurrenceRule<TData = RecurrenceRuleResponseDTO>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 reactivateRecurrenceRule<TData = RecurrenceRuleResponseDTO>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 reactivateRecurrenceRule<TData = RecurrenceRuleResponseDTO>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  reactivateRecurrenceRule<TData = RecurrenceRuleResponseDTO>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/recurrence-rules/${id}/reactivate`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/recurrence-rules/${id}/reactivate`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/recurrence-rules/${id}/reactivate`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Materializa uma ocorrência da regra como transação real
 */
 confirmOccurrence<TData = TransactionResponseDTO>(id: string,
    date: string,
    confirmOccurrenceDTO?: ConfirmOccurrenceDTO, options?: HttpClientBodyOptions): Observable<TData>;
 confirmOccurrence<TData = TransactionResponseDTO>(id: string,
    date: string,
    confirmOccurrenceDTO?: ConfirmOccurrenceDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 confirmOccurrence<TData = TransactionResponseDTO>(id: string,
    date: string,
    confirmOccurrenceDTO?: ConfirmOccurrenceDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  confirmOccurrence<TData = TransactionResponseDTO>(
    id: string,
    date: string,
    confirmOccurrenceDTO?: ConfirmOccurrenceDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/recurrence-rules/${id}/occurrences/${date}/confirm`,
      confirmOccurrenceDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/recurrence-rules/${id}/occurrences/${date}/confirm`,
      confirmOccurrenceDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/recurrence-rules/${id}/occurrences/${date}/confirm`,
      confirmOccurrenceDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Pula uma ocorrência (grava EXDATE)
 */
 skipOccurrence<TData = void>(id: string,
    date: string, options?: HttpClientBodyOptions): Observable<TData>;
 skipOccurrence<TData = void>(id: string,
    date: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 skipOccurrence<TData = void>(id: string,
    date: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  skipOccurrence<TData = void>(
    id: string,
    date: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/recurrence-rules/${id}/occurrences/${date}/skip`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/recurrence-rules/${id}/occurrences/${date}/skip`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/recurrence-rules/${id}/occurrences/${date}/skip`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

