/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Fintech SaaS API
 * API de gestão financeira multi-tenant.
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  TransactionRequestDTO,
  TransactionResponseDTO,
  TransactionUpdateDTO
} from '../fintechSaaSAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class TransactionsService {
  private readonly http = inject(HttpClient);
 listTransactions<TData = TransactionResponseDTO[]>( options?: HttpClientBodyOptions): Observable<TData>;
 listTransactions<TData = TransactionResponseDTO[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listTransactions<TData = TransactionResponseDTO[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listTransactions<TData = TransactionResponseDTO[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/transactions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/transactions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/transactions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 createTransaction<TData = TransactionResponseDTO[]>(transactionRequestDTO: TransactionRequestDTO, options?: HttpClientBodyOptions): Observable<TData>;
 createTransaction<TData = TransactionResponseDTO[]>(transactionRequestDTO: TransactionRequestDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 createTransaction<TData = TransactionResponseDTO[]>(transactionRequestDTO: TransactionRequestDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  createTransaction<TData = TransactionResponseDTO[]>(
    transactionRequestDTO: TransactionRequestDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/transactions`,
      transactionRequestDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/transactions`,
      transactionRequestDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/transactions`,
      transactionRequestDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getTransaction<TData = TransactionResponseDTO>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getTransaction<TData = TransactionResponseDTO>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getTransaction<TData = TransactionResponseDTO>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getTransaction<TData = TransactionResponseDTO>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/transactions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/transactions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/transactions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 updateTransaction<TData = TransactionResponseDTO>(id: string,
    transactionUpdateDTO: TransactionUpdateDTO, options?: HttpClientBodyOptions): Observable<TData>;
 updateTransaction<TData = TransactionResponseDTO>(id: string,
    transactionUpdateDTO: TransactionUpdateDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateTransaction<TData = TransactionResponseDTO>(id: string,
    transactionUpdateDTO: TransactionUpdateDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateTransaction<TData = TransactionResponseDTO>(
    id: string,
    transactionUpdateDTO: TransactionUpdateDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/transactions/${id}`,
      transactionUpdateDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/transactions/${id}`,
      transactionUpdateDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/transactions/${id}`,
      transactionUpdateDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteTransaction<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteTransaction<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteTransaction<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteTransaction<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/transactions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/transactions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/transactions/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

