/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Fintech SaaS API
 * API de gestão financeira multi-tenant.
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  LoginDTO,
  LoginResponseDTO,
  RegisterResponseDTO,
  TenantRegistrationDTO
} from '../fintechSaaSAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class AuthService {
  private readonly http = inject(HttpClient);
 login<TData = LoginResponseDTO>(loginDTO: LoginDTO, options?: HttpClientBodyOptions): Observable<TData>;
 login<TData = LoginResponseDTO>(loginDTO: LoginDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 login<TData = LoginResponseDTO>(loginDTO: LoginDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  login<TData = LoginResponseDTO>(
    loginDTO: LoginDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/auth/login`,
      loginDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/auth/login`,
      loginDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/auth/login`,
      loginDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 register<TData = RegisterResponseDTO>(tenantRegistrationDTO: TenantRegistrationDTO, options?: HttpClientBodyOptions): Observable<TData>;
 register<TData = RegisterResponseDTO>(tenantRegistrationDTO: TenantRegistrationDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 register<TData = RegisterResponseDTO>(tenantRegistrationDTO: TenantRegistrationDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  register<TData = RegisterResponseDTO>(
    tenantRegistrationDTO: TenantRegistrationDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/auth/register`,
      tenantRegistrationDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/auth/register`,
      tenantRegistrationDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/auth/register`,
      tenantRegistrationDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

export type LoginClientResult = NonNullable<LoginResponseDTO>
export type RegisterClientResult = NonNullable<RegisterResponseDTO>
