/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Fintech SaaS API
 * API de gestão financeira multi-tenant.
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  CreateCreditCardDTO,
  CreditCardResponseDTO,
  UpdateCreditCardDTO
} from '../fintechSaaSAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class CreditCardsService {
  private readonly http = inject(HttpClient);
 listCreditCards<TData = CreditCardResponseDTO[]>( options?: HttpClientBodyOptions): Observable<TData>;
 listCreditCards<TData = CreditCardResponseDTO[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listCreditCards<TData = CreditCardResponseDTO[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listCreditCards<TData = CreditCardResponseDTO[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/credit-cards`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/credit-cards`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/credit-cards`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 createCreditCard<TData = CreditCardResponseDTO>(createCreditCardDTO: CreateCreditCardDTO, options?: HttpClientBodyOptions): Observable<TData>;
 createCreditCard<TData = CreditCardResponseDTO>(createCreditCardDTO: CreateCreditCardDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 createCreditCard<TData = CreditCardResponseDTO>(createCreditCardDTO: CreateCreditCardDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  createCreditCard<TData = CreditCardResponseDTO>(
    createCreditCardDTO: CreateCreditCardDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/credit-cards`,
      createCreditCardDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/credit-cards`,
      createCreditCardDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/credit-cards`,
      createCreditCardDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getCreditCard<TData = CreditCardResponseDTO>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getCreditCard<TData = CreditCardResponseDTO>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getCreditCard<TData = CreditCardResponseDTO>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getCreditCard<TData = CreditCardResponseDTO>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/credit-cards/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/credit-cards/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/credit-cards/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 updateCreditCard<TData = CreditCardResponseDTO>(id: string,
    updateCreditCardDTO: UpdateCreditCardDTO, options?: HttpClientBodyOptions): Observable<TData>;
 updateCreditCard<TData = CreditCardResponseDTO>(id: string,
    updateCreditCardDTO: UpdateCreditCardDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateCreditCard<TData = CreditCardResponseDTO>(id: string,
    updateCreditCardDTO: UpdateCreditCardDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateCreditCard<TData = CreditCardResponseDTO>(
    id: string,
    updateCreditCardDTO: UpdateCreditCardDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/credit-cards/${id}`,
      updateCreditCardDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/credit-cards/${id}`,
      updateCreditCardDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/credit-cards/${id}`,
      updateCreditCardDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteCreditCard<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteCreditCard<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteCreditCard<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteCreditCard<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/credit-cards/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/credit-cards/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/credit-cards/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

