/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Fintech SaaS API
 * API de gestão financeira multi-tenant.
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  CreateImportBody,
  ImportBatchResponseDTO,
  ImportCommitRequestDTO,
  NormalizedBatchDTO,
  StagedPatchDTO,
  StagedTransactionResponseDTO
} from '../fintechSaaSAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class ImportsService {
  private readonly http = inject(HttpClient);
/**
 * Prova o pipeline ponta a ponta sem extrator real. Grava o batch (EXTRACTED) e as transações em staging (PENDING), derivando requires_review por threshold no backend.
 * @summary (dev) Cria um batch a partir de um schema normalizado mockado
 */
 createMockImport<TData = ImportBatchResponseDTO>(normalizedBatchDTO: NormalizedBatchDTO, options?: HttpClientBodyOptions): Observable<TData>;
 createMockImport<TData = ImportBatchResponseDTO>(normalizedBatchDTO: NormalizedBatchDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 createMockImport<TData = ImportBatchResponseDTO>(normalizedBatchDTO: NormalizedBatchDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  createMockImport<TData = ImportBatchResponseDTO>(
    normalizedBatchDTO: NormalizedBatchDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/imports/mock`,
      normalizedBatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/imports/mock`,
      normalizedBatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/imports/mock`,
      normalizedBatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Detalhe de um batch de importação
 */
 getImport<TData = ImportBatchResponseDTO>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getImport<TData = ImportBatchResponseDTO>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getImport<TData = ImportBatchResponseDTO>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getImport<TData = ImportBatchResponseDTO>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/imports/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/imports/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/imports/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Lista as transações em staging de um batch
 */
 listImportStaged<TData = StagedTransactionResponseDTO[]>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 listImportStaged<TData = StagedTransactionResponseDTO[]>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listImportStaged<TData = StagedTransactionResponseDTO[]>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listImportStaged<TData = StagedTransactionResponseDTO[]>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/imports/${id}/staged`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/imports/${id}/staged`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/imports/${id}/staged`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Multipart: envia a imagem (file) + o modo de importação. Aciona o VisionExtractor (Spring AI + Ollama), grava o batch EXTRACTED e a transação em staging (PENDING), derivando requires_review por threshold no backend. Falha de extração grava o batch como FAILED (o fallback é o formulário manual de transação).
 * @summary Extrai um comprovante (imagem) e cria um batch com a transação em staging
 */
 createImport<TData = ImportBatchResponseDTO>(createImportBody: CreateImportBody, options?: HttpClientBodyOptions): Observable<TData>;
 createImport<TData = ImportBatchResponseDTO>(createImportBody: CreateImportBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 createImport<TData = ImportBatchResponseDTO>(createImportBody: CreateImportBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  createImport<TData = ImportBatchResponseDTO>(
    createImportBody: CreateImportBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
formData.append(`file`, createImportBody.file);
formData.append(`importMode`, createImportBody.importMode);

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/imports`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/imports`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/imports`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Edita os campos de uma transação em staging antes de lançar
 */
 patchImportStaged<TData = StagedTransactionResponseDTO>(id: string,
    stagedId: string,
    stagedPatchDTO: StagedPatchDTO, options?: HttpClientBodyOptions): Observable<TData>;
 patchImportStaged<TData = StagedTransactionResponseDTO>(id: string,
    stagedId: string,
    stagedPatchDTO: StagedPatchDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 patchImportStaged<TData = StagedTransactionResponseDTO>(id: string,
    stagedId: string,
    stagedPatchDTO: StagedPatchDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  patchImportStaged<TData = StagedTransactionResponseDTO>(
    id: string,
    stagedId: string,
    stagedPatchDTO: StagedPatchDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/imports/${id}/staged/${stagedId}`,
      stagedPatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/imports/${id}/staged/${stagedId}`,
      stagedPatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/imports/${id}/staged/${stagedId}`,
      stagedPatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Para cada staged listada (PENDING), valida a sanidade (valor plausível, data coerente), cria a Transaction reusando o caminho de criação existente (débito→EXPENSE, crédito→INCOME; conta escolhida pelo usuário) e marca a staged CONFIRMED. O batch vira COMMITTED quando nenhuma staged fica mais PENDING.
 * @summary Promove as staged selecionadas a transações
 */
 commitImport<TData = ImportBatchResponseDTO>(id: string,
    importCommitRequestDTO: ImportCommitRequestDTO, options?: HttpClientBodyOptions): Observable<TData>;
 commitImport<TData = ImportBatchResponseDTO>(id: string,
    importCommitRequestDTO: ImportCommitRequestDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 commitImport<TData = ImportBatchResponseDTO>(id: string,
    importCommitRequestDTO: ImportCommitRequestDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  commitImport<TData = ImportBatchResponseDTO>(
    id: string,
    importCommitRequestDTO: ImportCommitRequestDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/imports/${id}/commit`,
      importCommitRequestDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/imports/${id}/commit`,
      importCommitRequestDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/imports/${id}/commit`,
      importCommitRequestDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

