spring.application.name=fintech-api

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fintech
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# IMPORTANTE: Desligamos o ddl-auto pois usaremos Flyway para criar tabelas
spring.jpa.hibernate.ddl-auto=validate