/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Fintech SaaS API
 * API de gestão financeira multi-tenant.
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  AccountCreateRequest,
  AccountResponse,
  AccountUpdateRequest
} from '../fintechSaaSAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class AccountsService {
  private readonly http = inject(HttpClient);
 listAccounts<TData = AccountResponse[]>( options?: HttpClientBodyOptions): Observable<TData>;
 listAccounts<TData = AccountResponse[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listAccounts<TData = AccountResponse[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listAccounts<TData = AccountResponse[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/accounts`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/accounts`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/accounts`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 createAccount<TData = AccountResponse>(accountCreateRequest: AccountCreateRequest, options?: HttpClientBodyOptions): Observable<TData>;
 createAccount<TData = AccountResponse>(accountCreateRequest: AccountCreateRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 createAccount<TData = AccountResponse>(accountCreateRequest: AccountCreateRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  createAccount<TData = AccountResponse>(
    accountCreateRequest: AccountCreateRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/accounts`,
      accountCreateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/accounts`,
      accountCreateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/accounts`,
      accountCreateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getAccount<TData = AccountResponse>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getAccount<TData = AccountResponse>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getAccount<TData = AccountResponse>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getAccount<TData = AccountResponse>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/accounts/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/accounts/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/accounts/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 updateAccount<TData = AccountResponse>(id: string,
    accountUpdateRequest: AccountUpdateRequest, options?: HttpClientBodyOptions): Observable<TData>;
 updateAccount<TData = AccountResponse>(id: string,
    accountUpdateRequest: AccountUpdateRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateAccount<TData = AccountResponse>(id: string,
    accountUpdateRequest: AccountUpdateRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateAccount<TData = AccountResponse>(
    id: string,
    accountUpdateRequest: AccountUpdateRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/accounts/${id}`,
      accountUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/accounts/${id}`,
      accountUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/accounts/${id}`,
      accountUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteAccount<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteAccount<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteAccount<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteAccount<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/accounts/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/accounts/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/accounts/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

