/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Fintech SaaS API
 * API de gestão financeira multi-tenant.
 * OpenAPI spec version: 1.0.0
 */
export type TransactionType = typeof TransactionType[keyof typeof TransactionType];


export const TransactionType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;

export type TransactionStatus = typeof TransactionStatus[keyof typeof TransactionStatus];


export const TransactionStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
} as const;

export type InvoiceStatus = typeof InvoiceStatus[keyof typeof InvoiceStatus];


export const InvoiceStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  PAID: 'PAID',
} as const;

export type CardBrand = typeof CardBrand[keyof typeof CardBrand];


export const CardBrand = {
  VISA: 'VISA',
  MASTERCARD: 'MASTERCARD',
  ELO: 'ELO',
  AMEX: 'AMEX',
  HIPERCARD: 'HIPERCARD',
  OTHER: 'OTHER',
} as const;

export interface LoginDTO {
  email: string;
  password: string;
}

export interface LoginResponseDTO {
  token?: string;
}

export interface TenantRegistrationDTO {
  name: string;
  /** @nullable */
  document?: string | null;
  adminName: string;
  adminEmail: string;
  password: string;
}

export interface RegisterResponseDTO {
  id?: string;
  name?: string;
}

export interface CategoryCreateDTO {
  name: string;
  icon: string;
  color: string;
  /** @nullable */
  parentId?: string | null;
  /**
     * Código de taxonomia padrão. null = não alterar valor existente.
     * @nullable
     */
  taxonomyCode?: string | null;
}

export interface CategoryResponseDTO {
  id: string;
  name: string;
  icon: string;
  color: string;
  /** @nullable */
  parentId?: string | null;
  archived: boolean;
  /**
     * Código semântico estável para benchmarking cross-tenant. null = categoria criada pelo usuário.
     * @nullable
     */
  taxonomyCode?: string | null;
  children: CategoryResponseDTO[];
}

export interface CategoryArchiveRequest {
  /** @nullable */
  targetCategoryId?: string | null;
}

export interface CategoryConflictResponse {
  transactionCount: number;
  message: string;
}

export interface TransactionRequestDTO {
  description: string;
  /** @minimum 0.01 */
  amount: number;
  date: string;
  type: TransactionType;
  status?: TransactionStatus | null;
  /** @nullable */
  totalInstallments?: number | null;
  /** @nullable */
  categoryId?: string | null;
  accountId: string;
}

export interface TransactionUpdateDTO {
  /** @nullable */
  description?: string | null;
  /**
     * @minimum 0.01
     * @nullable
     */
  amount?: number | null;
  /** @nullable */
  date?: string | null;
  type?: TransactionType | null;
  status?: TransactionStatus | null;
  /** @nullable */
  categoryId?: string | null;
  /** @nullable */
  accountId?: string | null;
  /** @nullable */
  propagate?: string[] | null;
}

export interface TransactionResponseDTO {
  id: string;
  description: string;
  amount: number;
  date: string;
  type: TransactionType;
  status: TransactionStatus;
  /** @nullable */
  installmentLabel?: string | null;
  /** @nullable */
  categoryName?: string | null;
  /** @nullable */
  categoryId?: string | null;
  categoryArchived?: boolean;
  /** @nullable */
  categoryPath?: string | null;
  /** @nullable */
  categoryIcon?: string | null;
  /** @nullable */
  accountName?: string | null;
  /** @nullable */
  accountId?: string | null;
  /** @nullable */
  transferId?: string | null;
  /** @nullable */
  installmentGroupId?: string | null;
  /** @nullable */
  installmentGroupDescription?: string | null;
  /** @nullable */
  installmentNumber?: number | null;
  /** @nullable */
  totalInstallments?: number | null;
  /** @nullable */
  invoiceId?: string | null;
  /** @nullable */
  invoiceDueDate?: string | null;
  invoiceStatus?: InvoiceStatus | null;
}

export interface InvoiceResponseDTO {
  id: string;
  accountId: string;
  accountName: string;
  referenceMonth: number;
  referenceYear: number;
  label: string;
  closingDate: string;
  dueDate: string;
  status: InvoiceStatus;
  totalAmount: number;
  transactionCount: number;
}

export interface InvoicePayDTO {
  sourceAccountId: string;
}

export type DeleteInstallmentScope = typeof DeleteInstallmentScope[keyof typeof DeleteInstallmentScope];


export const DeleteInstallmentScope = {
  SINGLE: 'SINGLE',
  THIS_AND_NEXT: 'THIS_AND_NEXT',
  ALL: 'ALL',
} as const;

export interface DeleteInstallmentResultDTO {
  deleted: number;
  skippedPaid: number;
}

export interface InstallmentGroupPatchDTO {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  categoryId?: string | null;
  /** @nullable */
  accountId?: string | null;
  /** @nullable */
  installmentAmount?: number | null;
  status?: TransactionStatus | null;
  fields?: string[];
}

export interface InstallmentGroupResponseDTO {
  id: string;
  description: string;
  totalAmount: number;
  installmentAmount: number;
  totalInstallments: number;
  paidInstallments: number;
  pendingInstallments: number;
  /** @nullable */
  nextDueDate?: string | null;
  /** @nullable */
  categoryName?: string | null;
  /** @nullable */
  categoryId?: string | null;
  accountName: string;
  accountId?: string;
  transactions: TransactionResponseDTO[];
}

export interface TransferRequest {
  fromAccountId: string;
  toAccountId: string;
  /** @minimum 0.01 */
  amount: number;
  date: string;
  /** @nullable */
  description?: string | null;
}

export interface TransferResponse {
  transferId?: string;
  fromLegId?: string;
  toLegId?: string;
  amount?: number;
  date?: string;
  description?: string;
  fromAccount?: string;
  toAccount?: string;
}

export interface DashboardSummaryDTO {
  /** @pattern ^\d{4}-\d{2}$ */
  period?: string;
  totalIncome?: number;
  totalExpense?: number;
  balance?: number;
  /** Quantidade de transações não canceladas no período. Zero indica mês sem movimentação. */
  transactionCount?: number;
  /** Saldo líquido acumulado (todas as contas com countInLiquidBalance=true, sem filtro de período). */
  totalAccountBalance?: number;
}

export type AccountType = typeof AccountType[keyof typeof AccountType];


export const AccountType = {
  CHECKING: 'CHECKING',
  INVESTMENT: 'INVESTMENT',
  CREDIT_CARD: 'CREDIT_CARD',
  CASH: 'CASH',
} as const;

export interface CreditCardDetailsRequest {
  brand?: CardBrand;
  /**
     * @minLength 4
     * @maxLength 4
     * @nullable
     */
  lastFourDigits?: string | null;
  /** @nullable */
  limitAmount?: number | null;
  /**
     * @minimum 1
     * @maximum 31
     * @nullable
     */
  closingDay?: number | null;
  /**
     * @minimum 1
     * @maximum 31
     * @nullable
     */
  dueDay?: number | null;
}

export interface CreditCardDetailsResponse {
  brand?: CardBrand | null;
  /** @nullable */
  lastFourDigits?: string | null;
  /** @nullable */
  limitAmount?: number | null;
  closingDay: number;
  dueDay: number;
}

export interface AccountCreateRequest {
  /** @maxLength 100 */
  name: string;
  type: AccountType;
  /**
     * @nullable
     * @pattern ^#([A-Fa-f0-9]{6})$
     */
  color?: string | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  countInLiquidBalance?: boolean | null;
  /** @nullable */
  countInNetWorth?: boolean | null;
  creditCardDetails?: CreditCardDetailsRequest | null;
}

export interface AccountUpdateRequest {
  /**
     * @maxLength 100
     * @nullable
     */
  name?: string | null;
  /**
     * @nullable
     * @pattern ^#([A-Fa-f0-9]{6})$
     */
  color?: string | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  countInLiquidBalance?: boolean | null;
  /** @nullable */
  countInNetWorth?: boolean | null;
  creditCardDetails?: CreditCardDetailsRequest | null;
}

export interface AccountResponse {
  id: string;
  name: string;
  type: AccountType;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  icon?: string | null;
  countInLiquidBalance: boolean;
  countInNetWorth: boolean;
  active: boolean;
  balance: number;
  creditCardDetails?: CreditCardDetailsResponse | null;
}

export type ListCategoriesParams = {
includeArchived?: boolean;
};

export type ListTransactionsParams = {
invoiceId?: string;
accountIds?: string[];
status?: TransactionStatus;
type?: TransactionType;
startDate?: string;
endDate?: string;
};

export type DeleteTransactionParams = {
scope?: DeleteInstallmentScope;
};

export type GetDashboardSummaryParams = {
/**
 * Mês no formato yyyy-MM
 */
month: string;
};

export type ListInvoicesParams = {
accountId: string;
};

