/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Fintech SaaS API
 * API de gestão financeira multi-tenant.
 * OpenAPI spec version: 1.0.0
 */
export type TransactionType = typeof TransactionType[keyof typeof TransactionType];


export const TransactionType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  TRANSFER: 'TRANSFER',
} as const;

export type TransactionStatus = typeof TransactionStatus[keyof typeof TransactionStatus];


export const TransactionStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
} as const;

export type CardBrand = typeof CardBrand[keyof typeof CardBrand];


export const CardBrand = {
  VISA: 'VISA',
  MASTERCARD: 'MASTERCARD',
  ELO: 'ELO',
  AMEX: 'AMEX',
  HIPERCARD: 'HIPERCARD',
  OTHER: 'OTHER',
} as const;

export interface LoginDTO {
  email: string;
  password: string;
}

export interface LoginResponseDTO {
  token?: string;
}

export interface TenantRegistrationDTO {
  name: string;
  /** @nullable */
  document?: string | null;
  adminName: string;
  adminEmail: string;
  password: string;
}

export interface RegisterResponseDTO {
  id?: string;
  name?: string;
}

export interface CategoryCreateDTO {
  name: string;
  icon: string;
  color: string;
  /** @nullable */
  parentId?: string | null;
}

export interface CategoryResponseDTO {
  id?: string;
  name?: string;
  icon?: string;
  color?: string;
  /** @nullable */
  parentId?: string | null;
  children?: CategoryResponseDTO[];
}

export interface TransactionRequestDTO {
  description: string;
  /** @minimum 0.01 */
  amount: number;
  date: string;
  type: TransactionType;
  status?: TransactionStatus | null;
  /** @nullable */
  totalInstallments?: number | null;
  /** @nullable */
  categoryId?: string | null;
  /** @nullable */
  creditCardId?: string | null;
}

export interface TransactionUpdateDTO {
  /** @nullable */
  description?: string | null;
  /**
     * @minimum 0.01
     * @nullable
     */
  amount?: number | null;
  /** @nullable */
  date?: string | null;
  type?: TransactionType | null;
  status?: TransactionStatus | null;
  /** @nullable */
  categoryId?: string | null;
  /** @nullable */
  creditCardId?: string | null;
}

export interface TransactionResponseDTO {
  id?: string;
  description?: string;
  amount?: number;
  date?: string;
  type?: TransactionType;
  status?: TransactionStatus;
  /** @nullable */
  installmentLabel?: string | null;
  /** @nullable */
  categoryName?: string | null;
  /** @nullable */
  creditCardName?: string | null;
}

export interface DashboardSummaryDTO {
  /** @pattern ^\d{4}-\d{2}$ */
  period?: string;
  totalIncome?: number;
  totalExpense?: number;
  balance?: number;
}

export interface CreateCreditCardDTO {
  name: string;
  brand: CardBrand;
  /**
     * @nullable
     * @pattern ^#([A-Fa-f0-9]{6})$
     */
  color?: string | null;
  /**
     * @minLength 4
     * @maxLength 4
     * @nullable
     */
  lastFourDigits?: string | null;
  /** @minimum 0.01 */
  limitAmount: number;
  /**
     * @minimum 1
     * @maximum 31
     */
  closingDay: number;
  /**
     * @minimum 1
     * @maximum 31
     */
  dueDay: number;
}

export interface CreditCardResponseDTO {
  id?: string;
  name?: string;
  brand?: CardBrand;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  lastFourDigits?: string | null;
  limitAmount?: number;
  closingDay?: number;
  dueDay?: number;
}

export interface UpdateCreditCardDTO {
  /** @nullable */
  name?: string | null;
  /**
     * @nullable
     * @pattern ^#([A-Fa-f0-9]{6})$
     */
  color?: string | null;
  /** @nullable */
  lastFourDigits?: string | null;
  /** @nullable */
  limitAmount?: number | null;
  /** @nullable */
  closingDay?: number | null;
  /** @nullable */
  dueDay?: number | null;
}

export type GetDashboardSummaryParams = {
/**
 * Mês no formato yyyy-MM
 */
month: string;
};

