/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Fintech SaaS API
 * API de gestão financeira multi-tenant.
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  DeleteInstallmentResultDTO,
  InstallmentGroupPatchDTO,
  InstallmentGroupResponseDTO
} from '../fintechSaaSAPI.schemas';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class InstallmentGroupsService {
  private readonly http = inject(HttpClient);
 listInstallmentGroups<TData = InstallmentGroupResponseDTO[]>( options?: HttpClientBodyOptions): Observable<TData>;
 listInstallmentGroups<TData = InstallmentGroupResponseDTO[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listInstallmentGroups<TData = InstallmentGroupResponseDTO[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listInstallmentGroups<TData = InstallmentGroupResponseDTO[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/installment-groups`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/installment-groups`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/installment-groups`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 getInstallmentGroup<TData = InstallmentGroupResponseDTO>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 getInstallmentGroup<TData = InstallmentGroupResponseDTO>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getInstallmentGroup<TData = InstallmentGroupResponseDTO>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getInstallmentGroup<TData = InstallmentGroupResponseDTO>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/installment-groups/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/installment-groups/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/installment-groups/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 deleteInstallmentGroup<TData = DeleteInstallmentResultDTO>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteInstallmentGroup<TData = DeleteInstallmentResultDTO>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteInstallmentGroup<TData = DeleteInstallmentResultDTO>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteInstallmentGroup<TData = DeleteInstallmentResultDTO>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/installment-groups/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/installment-groups/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/installment-groups/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
 patchInstallmentGroup<TData = InstallmentGroupResponseDTO>(id: string,
    installmentGroupPatchDTO: InstallmentGroupPatchDTO, options?: HttpClientBodyOptions): Observable<TData>;
 patchInstallmentGroup<TData = InstallmentGroupResponseDTO>(id: string,
    installmentGroupPatchDTO: InstallmentGroupPatchDTO, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 patchInstallmentGroup<TData = InstallmentGroupResponseDTO>(id: string,
    installmentGroupPatchDTO: InstallmentGroupPatchDTO, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  patchInstallmentGroup<TData = InstallmentGroupResponseDTO>(
    id: string,
    installmentGroupPatchDTO: InstallmentGroupPatchDTO, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/installment-groups/${id}`,
      installmentGroupPatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/installment-groups/${id}`,
      installmentGroupPatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/installment-groups/${id}`,
      installmentGroupPatchDTO,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

